# Generated by Django 4.2.26 on 2025-11-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_post_options_chat_message'),
        ('main', '0006_alter_userrating_rating'),
    ]

    operations = [
    ]
