# Generated by Django 5.2.8 on 2025-11-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_notification_postcomment_postlike_post_image_and_more'),
        ('main', '0009_alter_community_options_alter_post_options_and_more'),
    ]

    operations = [
    ]
