# Generated by Django 4.2.26 on 2025-11-22 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='theme',
            field=models.CharField(choices=[('music', 'Музыка'), ('psychology', 'Психология'), ('sport', 'Спорт'), ('games', 'Компьютерные игры'), ('development', 'Развитие'), ('board_games', 'Настольные игры'), ('programming', 'Программирование'), ('schools', 'Школы'), ('design', 'Дизайн'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тематика'),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='groups/posts/images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название сообщества'),
        ),
        migrations.CreateModel(
            name='GroupPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_post_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='groups.grouppost', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Комментарий к посту группы',
                'verbose_name_plural': 'Комментарии к постам групп',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='GroupPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата лайка')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='groups.grouppost', verbose_name='Пост')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_post_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лайк поста группы',
                'verbose_name_plural': 'Лайки постов групп',
                'unique_together': {('post', 'user')},
            },
        ),
    ]
